"""Model specification catalog for auto-fit planning."""

from typing import Any, Dict, List, Optional
from .models import ModelSpec, PrecisionType

_CATALOG: Dict[str, ModelSpec] = {
    "meta-llama/Llama-3.2-3B-Instruct": ModelSpec(
        model_id="meta-llama/Llama-3.2-3B-Instruct",
        display_name="Llama 3.2 3B Instruct (LocalMind Default)",
        parameter_count_b=3.21,
        num_layers=28,
        hidden_size=3072,
        num_attention_heads=24,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="meta-llama/Llama-3.2-3B-Instruct",
        ollama_model_id="llama3.2:3b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "meta-llama/Llama-3.2-3B-Instruct",
            "awq": "hugging-quants/Llama-3.2-3B-Instruct-AWQ-INT4",
            "fp8": "neuralmagic/Llama-3.2-3B-Instruct-FP8",
            "q4_k_m": "llama-3.2-3b-instruct.Q4_K_M.gguf",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "meta-llama/Llama-3.2-1B-Instruct": ModelSpec(
        model_id="meta-llama/Llama-3.2-1B-Instruct",
        display_name="Llama 3.2 1B Instruct",
        parameter_count_b=1.23,
        num_layers=16,
        hidden_size=2048,
        num_attention_heads=32,
        num_kv_heads=8,
        head_dim=64,
        hf_repo_id="meta-llama/Llama-3.2-1B-Instruct",
        ollama_model_id="llama3.2:1b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "meta-llama/Llama-3.2-1B-Instruct",
            "fp8": "neuralmagic/Llama-3.2-1B-Instruct-FP8",
            "q4_k_m": "llama-3.2-1b-instruct.Q4_K_M.gguf",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "meta-llama/Meta-Llama-3.1-8B-Instruct": ModelSpec(
        model_id="meta-llama/Meta-Llama-3.1-8B-Instruct",
        display_name="Llama 3.1 8B Instruct",
        parameter_count_b=8.03,
        num_layers=32,
        hidden_size=4096,
        num_attention_heads=32,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="meta-llama/Meta-Llama-3.1-8B-Instruct",
        ollama_model_id="llama3.1:8b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "meta-llama/Meta-Llama-3.1-8B-Instruct",
            "awq": "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4",
            "fp8": "neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8",
            "q4_k_m": "llama-3.1-8b-instruct.Q4_K_M.gguf",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "meta-llama/Meta-Llama-3.1-70B-Instruct": ModelSpec(
        model_id="meta-llama/Meta-Llama-3.1-70B-Instruct",
        display_name="Llama 3.1 70B Instruct",
        parameter_count_b=70.6,
        num_layers=80,
        hidden_size=8192,
        num_attention_heads=64,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="meta-llama/Meta-Llama-3.1-70B-Instruct",
        ollama_model_id="llama3.1:70b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "meta-llama/Meta-Llama-3.1-70B-Instruct",
            "awq": "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4",
            "fp8": "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "Qwen/Qwen2.5-7B-Instruct": ModelSpec(
        model_id="Qwen/Qwen2.5-7B-Instruct",
        display_name="Qwen 2.5 7B Instruct",
        parameter_count_b=7.61,
        num_layers=28,
        hidden_size=3584,
        num_attention_heads=28,
        num_kv_heads=4,
        head_dim=128,
        hf_repo_id="Qwen/Qwen2.5-7B-Instruct",
        ollama_model_id="qwen2.5:7b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "Qwen/Qwen2.5-7B-Instruct",
            "awq": "Qwen/Qwen2.5-7B-Instruct-AWQ",
            "fp8": "neuralmagic/Qwen2.5-7B-Instruct-FP8",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "Qwen/Qwen2.5-14B-Instruct": ModelSpec(
        model_id="Qwen/Qwen2.5-14B-Instruct",
        display_name="Qwen 2.5 14B Instruct",
        parameter_count_b=14.7,
        num_layers=48,
        hidden_size=5120,
        num_attention_heads=40,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="Qwen/Qwen2.5-14B-Instruct",
        ollama_model_id="qwen2.5:14b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "Qwen/Qwen2.5-14B-Instruct",
            "awq": "Qwen/Qwen2.5-14B-Instruct-AWQ",
            "fp8": "neuralmagic/Qwen2.5-14B-Instruct-FP8",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "Qwen/Qwen2.5-32B-Instruct": ModelSpec(
        model_id="Qwen/Qwen2.5-32B-Instruct",
        display_name="Qwen 2.5 32B Instruct",
        parameter_count_b=32.5,
        num_layers=64,
        hidden_size=5120,
        num_attention_heads=40,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="Qwen/Qwen2.5-32B-Instruct",
        ollama_model_id="qwen2.5:32b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "Qwen/Qwen2.5-32B-Instruct",
            "awq": "Qwen/Qwen2.5-32B-Instruct-AWQ",
            "fp8": "neuralmagic/Qwen2.5-32B-Instruct-FP8",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "Qwen/Qwen2.5-72B-Instruct": ModelSpec(
        model_id="Qwen/Qwen2.5-72B-Instruct",
        display_name="Qwen 2.5 72B Instruct",
        parameter_count_b=72.7,
        num_layers=80,
        hidden_size=8192,
        num_attention_heads=64,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="Qwen/Qwen2.5-72B-Instruct",
        ollama_model_id="qwen2.5:72b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "Qwen/Qwen2.5-72B-Instruct",
            "awq": "Qwen/Qwen2.5-72B-Instruct-AWQ",
            "fp8": "neuralmagic/Qwen2.5-72B-Instruct-FP8",
        },
        max_context_len=131072,
        default_context_len=8192,
    ),
    "google/gemma-2-9b-it": ModelSpec(
        model_id="google/gemma-2-9b-it",
        display_name="Gemma 2 9B IT",
        parameter_count_b=9.24,
        num_layers=42,
        hidden_size=3584,
        num_attention_heads=16,
        num_kv_heads=8,
        head_dim=256,
        hf_repo_id="google/gemma-2-9b-it",
        ollama_model_id="gemma2:9b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "google/gemma-2-9b-it",
            "fp8": "neuralmagic/gemma-2-9b-it-FP8",
        },
        max_context_len=8192,
        default_context_len=8192,
    ),
    "google/gemma-2-27b-it": ModelSpec(
        model_id="google/gemma-2-27b-it",
        display_name="Gemma 2 27B IT",
        parameter_count_b=27.2,
        num_layers=46,
        hidden_size=4608,
        num_attention_heads=32,
        num_kv_heads=16,
        head_dim=128,
        hf_repo_id="google/gemma-2-27b-it",
        ollama_model_id="gemma2:27b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "google/gemma-2-27b-it",
            "fp8": "neuralmagic/gemma-2-27b-it-FP8",
        },
        max_context_len=8192,
        default_context_len=8192,
    ),
    "mistralai/Mistral-7B-Instruct-v0.3": ModelSpec(
        model_id="mistralai/Mistral-7B-Instruct-v0.3",
        display_name="Mistral 7B Instruct v0.3",
        parameter_count_b=7.25,
        num_layers=32,
        hidden_size=4096,
        num_attention_heads=32,
        num_kv_heads=8,
        head_dim=128,
        hf_repo_id="mistralai/Mistral-7B-Instruct-v0.3",
        ollama_model_id="mistral:7b",
        exact_model_revision="main",
        available_weight_formats=["safetensors"],
        registered_quantizations={
            "none": "mistralai/Mistral-7B-Instruct-v0.3",
            "awq": "hugging-quants/Mistral-7B-Instruct-v0.3-AWQ-INT4",
            "fp8": "neuralmagic/Mistral-7B-Instruct-v0.3-FP8",
        },
        max_context_len=32768,
        default_context_len=8192,
    ),
}

# Aliases for convenience
_ALIASES = {
    "llama3.2:3b": "meta-llama/Llama-3.2-3B-Instruct",
    "llama3.2:1b": "meta-llama/Llama-3.2-1B-Instruct",
    "llama3:8b": "meta-llama/Meta-Llama-3.1-8B-Instruct",
    "llama3.1:8b": "meta-llama/Meta-Llama-3.1-8B-Instruct",
    "llama3:70b": "meta-llama/Meta-Llama-3.1-70B-Instruct",
    "llama3.1:70b": "meta-llama/Meta-Llama-3.1-70B-Instruct",
    "qwen2.5:7b": "Qwen/Qwen2.5-7B-Instruct",
    "qwen2.5:14b": "Qwen/Qwen2.5-14B-Instruct",
    "qwen2.5:32b": "Qwen/Qwen2.5-32B-Instruct",
    "qwen2.5:72b": "Qwen/Qwen2.5-72B-Instruct",
    "gemma2:9b": "google/gemma-2-9b-it",
    "gemma2:27b": "google/gemma-2-27b-it",
    "mistral:7b": "mistralai/Mistral-7B-Instruct-v0.3",
}


def get_model_spec(model_id: str) -> Optional[ModelSpec]:
    normalized = model_id.strip()
    if normalized in _CATALOG:
        return _CATALOG[normalized]
    if normalized.lower() in _ALIASES:
        return _CATALOG[_ALIASES[normalized.lower()]]
    return None


def list_supported_models() -> List[Dict[str, Any]]:
    return [
        {
            "model_id": spec.model_id,
            "display_name": spec.display_name,
            "parameters_billion": spec.parameter_count_b,
            "max_context": spec.max_context_len,
            "ollama_id": spec.ollama_model_id,
            "hf_id": spec.hf_repo_id,
            "has_awq": "awq" in spec.registered_quantizations,
            "has_fp8": "fp8" in spec.registered_quantizations,
        }
        for spec in _CATALOG.values()
    ]
