"""add_cdc_and_job_columns

Revision ID: fafe1f524764
Revises: c498a129d10e
Create Date: 2026-09-16 20:56:44.983147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafe1f524764'
down_revision: Union[str, Sequence[str], None] = 'c498a129d10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_documents', sa.Column('job_id', sa.String(length=36), nullable=True))
    op.add_column('enterprise_documents', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('enterprise_documents', sa.Column('external_last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_enterprise_documents_external_id'), 'enterprise_documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_enterprise_documents_job_id'), 'enterprise_documents', ['job_id'], unique=False)
    op.create_foreign_key(None, 'enterprise_documents', 'ingestion_jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.add_column('ingestion_jobs', sa.Column('last_sync_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'last_sync_token')
    op.drop_constraint(None, 'enterprise_documents', type_='foreignkey')
    op.drop_index(op.f('ix_enterprise_documents_job_id'), table_name='enterprise_documents')
    op.drop_index(op.f('ix_enterprise_documents_external_id'), table_name='enterprise_documents')
    op.drop_column('enterprise_documents', 'external_last_modified')
    op.drop_column('enterprise_documents', 'external_id')
    op.drop_column('enterprise_documents', 'job_id')
    # ### end Alembic commands ###
