name: multi-tenant-rag-system

include:
  - docker-compose.storage.yml

services:
  wings_retrival_ai:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wings_retrival_ai
    working_dir: /app
    ports:
      - "4500:4500"
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
    command: python -m uvicorn app.main:app --app-dir /app --host 0.0.0.0 --port 4500 --reload
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  wings_ingestion_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wings_ingestion_worker
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
    command: python -m celery -A modules.tasks.celery_app worker --loglevel=info
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_started
    restart: always

networks:
  default:
    name: rag_network
